# Generated by Django 3.0.7 on 2020-08-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=15)),
                ('celular', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('cedula', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('mascota_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_mas', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('turnos_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('atencion', 'Atencion'), ('estilista', 'Estilista')], max_length=30)),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('descripcion', models.TextField(default='descripción de la transacción')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.Mascota')),
            ],
        ),
    ]
