# Generated by Django 3.0.7 on 2020-08-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_auto_20200815_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='valor',
        ),
    ]
