# Generated by Django 3.0.7 on 2020-08-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_remove_turnos_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_id',
            new_name='id',
        ),
    ]
