# Generated by Django 3.0.7 on 2020-08-16 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20200815_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='nombres',
            new_name='nombres_mas',
        ),
    ]
